# name: Deploy HTML to Nginx

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up SSH
#       uses: webfactory/ssh-agent@v0.5.4
#       with:
#         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#     - name: Deploy to server
#       run: |
#         rsync -avz --delete \
#         -e "ssh -o StrictHostKeyChecking=no" \
#         ./ root@${{ secrets.SERVER_IP }}:/var/www/web/


name: Deploy HTML to Nginx (Debugging)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to staging directory
      run: |
        rsync -avz --delete \
        -e "ssh -o StrictHostKeyChecking=no" \
        ./ root@${{ secrets.SERVER_IP }}:/var/www/staging/

    - name: Swap directories
      run: |
        ssh root@${{ secrets.SERVER_IP }} << EOF
          mv /var/www/web /var/www/backup_$(date +%Y%m%d%H%M%S)
          mv /var/www/staging /var/www/web
        EOF

    - name: Reload Nginx
      run: |
        ssh root@${{ secrets.SERVER_IP }} << EOF
          nginx -t && systemctl reload nginx
        EOF

    - name: Verify web directory
      run: |
        ssh root@${{ secrets.SERVER_IP }} << EOF
          ls -la /var/www/web/
        EOF
